### ISSUE TITLE
Code is not updated

### ISSUE THREAD

**Issue by gkocyigit** [Alecaddd/gutenberg-tutorial#2]
This code in this repo is not the same with the youtube series. I think you forgot to upload here. Can you please fix it?

**Comment by alessandrofilira** [comment]
Hi @gkocyigit, I think you have to check others branches, I had same problem but I found code there.

**Comment by Alecaddd** [comment]
Each lesson is uploaded in a dedicated branch.
Check the various branches matching the lesson number.
